services:
  # Backend development with hot-reload
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: planetplant-dev-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "9229:9229"  # Node.js debugging port
    environment:
      - NODE_ENV=development
      - DEBUG=planetplant:*
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=plantplant-super-secret-auth-token
      - INFLUXDB_ORG=planetplant
      - INFLUXDB_BUCKET=sensor-data
      - MQTT_BROKER_URL=mqtt://mosquitto:1883
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=plantplant123
    volumes:
      - ./:/app
      - /app/node_modules
      - backend_dev_data:/app/data
      - backend_dev_logs:/app/logs
    depends_on:
      - influxdb
      - mosquitto  
      - redis
    networks:
      - planetplant-dev-network

  # Frontend development with Vite
  frontend-dev:
    build:
      context: ../webapp
      dockerfile: Dockerfile.dev
    container_name: planetplant-dev-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000/api
      - VITE_SOCKET_URL=http://localhost:3000
    volumes:
      - ../webapp:/app
      - /app/node_modules
    networks:
      - planetplant-dev-network

  # InfluxDB for time-series data
  influxdb:
    image: influxdb:2.7-alpine
    container_name: planetplant-dev-influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=plantplant123
      - DOCKER_INFLUXDB_INIT_ORG=planetplant
      - DOCKER_INFLUXDB_INIT_BUCKET=sensor-data
      - DOCKER_INFLUXDB_INIT_RETENTION=90d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=plantplant-super-secret-auth-token
    volumes:
      - influxdb_dev_data:/var/lib/influxdb2
      - influxdb_dev_config:/etc/influxdb2
    networks:
      - planetplant-dev-network

  # MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: planetplant-dev-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ../config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_dev_data:/mosquitto/data
      - mosquitto_dev_logs:/mosquitto/log
    networks:
      - planetplant-dev-network

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: planetplant-dev-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass plantplant123
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - planetplant-dev-network

volumes:
  influxdb_dev_data:
    driver: local
  influxdb_dev_config:
    driver: local
  mosquitto_dev_data:
    driver: local
  mosquitto_dev_logs:
    driver: local
  redis_dev_data:
    driver: local
  backend_dev_data:
    driver: local
  backend_dev_logs:
    driver: local

networks:
  planetplant-dev-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16